### ISSUE TITLE
ROS path error

### ISSUE THREAD

**Issue by ShreyaIAB** [aliaxam153/ORB_SLAM3#2]
![Screenshot_ros](https://github.com/aliaxam153/ORB_SLAM3/assets/156421818/821f6195-c0ec-47fa-807c-1bede548c2e4)

I saw in the tutorial that you had a similar error, however even after executing the **source ~/.bashrc**, the issue is not fixed. this error arises when i execute the lines - 

cd Examples/ROS/ORB_SLAM3
mkdir build
cd build
**cmake .. -DROS_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3** - problem line
make -j

**Comment by ShreyaIAB** [comment]
![Screenshot_wsl2](https://github.com/aliaxam153/ORB_SLAM3/assets/156421818/daad755c-6ee8-4564-a6d9-466ad1076f54)

**Comment by aliaxam153** [comment]
Make sure to paste the rospackage path after this line in your .bashrc file;
```
source /opt/ros/noetic/setup.bash
```
Then, source the file:
```
source ~/.bashrc
```

**Comment by aliaxam153** [comment]
Also make sure to replace the user in the path with your username:

```
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/user/dev/ORB_SLAM3/Examples/ROS
```
After doing this rebuild ORB_SLAM3 ROS package only.

**Comment by ShreyaIAB** [comment]
thanks for your replies. I believe i have done the same steps suggested by you.
![Screenshot wsl3](https://github.com/aliaxam153/ORB_SLAM3/assets/156421818/52679a77-20b2-4268-9893-499ea39746bb)
and then 
![Screenshot wsl4](https://github.com/aliaxam153/ORB_SLAM3/assets/156421818/61407ad1-dbb5-4404-95c7-5ec9a992eaa6)
 however, i still get the same error as before when i execute cmake .. **-DROS_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3**

**Comment by ShreyaIAB** [comment]
After doing this rebuild ORB_SLAM3 ROS package only. --- what does this mean?

**Comment by aliaxam153** [comment]
> thanks for your replies. I believe i have done the same steps suggested by you.
> ![Screenshot wsl3](https://github.com/aliaxam153/ORB_SLAM3/assets/156421818/52679a77-20b2-4268-9893-499ea39746bb)
> and then 
> ![Screenshot wsl4](https://github.com/aliaxam153/ORB_SLAM3/assets/156421818/61407ad1-dbb5-4404-95c7-5ec9a992eaa6)
>  however, i still get the same error as before when i execute cmake .. **-DROS_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3**
> 

delete the last line in the bashrc. This line after export ROS:
```
source /opt/ros/noetic/setup.bash
```

 And then source the bashrc file again.

**Comment by aliaxam153** [comment]
> After doing this rebuild ORB_SLAM3 ROS package only. --- what does this mean?
> 
By that I mean, run these commands again:
```
chmod +x build_ros.sh
./build_ros.sh
```

**Comment by ShreyaIAB** [comment]
thanks i will try and let u know

**Comment by aliaxam153** [comment]
I have updated the bash file you can download it again. It should now install without any errors.

**Comment by ShreyaIAB** [comment]
Thanks. it was helpful beyond imagination for me :). Its running super good. i will make the updates in my local
